with-expecter: True
packages:
    github.com/alextanhongpin/go-domain-test/usecase:
        interfaces:
            productRepository:
                config:
                    # Change private lowercase interface to uppercase.
                    mockname: "MockProductRepository"
            purchaseRepository:
                config:
                    # Change private lowercase interface to uppercase.
                    mockname: "MockPurchaseRepository"
